# Generated by Django 4.1.1 on 2022-10-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_Name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='expert',
            name='expert_Topics',
        ),
        migrations.AddField(
            model_name='expert',
            name='expert_Topics',
            field=models.ManyToManyField(to='experts.topic'),
        ),
    ]
