# Generated by Django 4.1.1 on 2022-10-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_topic_remove_expert_expert_topics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_Name', models.TextField()),
                ('news_Description', models.TextField()),
                ('new_Link', models.URLField()),
            ],
        ),
    ]
