# Generated by Django 4.1.1 on 2022-10-11 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='news_Expert',
            field=models.ManyToManyField(to='experts.expert'),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='expert_College',
            field=models.CharField(choices=[('Arts and Sciences', 'Arts and Sciences'), ('AgricultureLifeSciences', 'Agriculture and Life Sciences'), ('ArchitechtureArtDesign', 'Architechture, Art and Design'), ('Business', 'Business'), ('Education', 'Education'), ('Forest Resources', 'Forest Resources'), ('Veterninary Medicine', 'Veterninary Medicine'), ('Engineering', 'James Worth Bagley College of Engineering'), ('ShackoulsHonors', 'Shackouls Honors College')], max_length=24),
        ),
    ]
