# Generated by Django 4.1.1 on 2022-10-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_expert_created_at_expert_updated_at_news_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='new_Link',
            new_name='news_Link',
        ),
        migrations.AddField(
            model_name='news',
            name='news_Link_Description',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
