# Generated by Django 4.1.7 on 2023-03-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0005_rename_new_link_news_news_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_Picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
