# Generated by Django 4.1.7 on 2023-04-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0005_rename_new_link_news_news_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='expert',
            name='expert_Picture',
            field=models.ImageField(upload_to='expertPic'),
        ),
        migrations.AddField(
            model_name='expert',
            name='expert_Links',
            field=models.ManyToManyField(to='experts.link'),
        ),
    ]
