# Generated by Django 4.1.7 on 2023-03-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0006_news_news_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_Picture',
        ),
        migrations.AddField(
            model_name='news',
            name='news_Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
