# Generated by Django 4.1.7 on 2023-04-21 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0006_link_alter_expert_expert_picture_expert_expert_links'),
        ('experts', '0007_remove_news_news_picture_news_news_image'),
    ]

    operations = [
    ]
